import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const playClicked = useState(false);

  useEffect(() => {
    if (playClicked) {
      const audio = new Audio("xmas.mpe");
      audio.volume = parseFloat(1);
      audio.play();
    }
  }, [playClicked]);

  return (
    <div className={styles.container}>
      <Head>
        <title>New Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Scattergories</h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>New Game</h2>
          </a>
        </div>
      </main>
    </div>
  );
}
